<a href="https://colab.research.google.com/github/devshub21/Heart-disease-prediction-using-ML/blob/main/Heart_Attack_Prediction_Random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('data.csv')
print(dataset)

      age  sex  chest pain type  ...  oldpeak  ST slope  target
0      40    1                2  ...      0.0         1       0
1      49    0                3  ...      1.0         2       1
2      37    1                2  ...      0.0         1       0
3      48    0                4  ...      1.5         2       1
4      54    1                3  ...      0.0         1       0
...   ...  ...              ...  ...      ...       ...     ...
1185   45    1                1  ...      1.2         2       1
1186   68    1                4  ...      3.4         2       1
1187   57    1                4  ...      1.2         2       1
1188   57    0                2  ...      0.0         2       1
1189   38    1                3  ...      0.0         1       0

[1190 rows x 12 columns]


In [ ]:
X = dataset.iloc[:,0:11]
Y = dataset.iloc[:,11]
print(X)
print(Y)

      age  sex  chest pain type  ...  exercise angina  oldpeak  ST slope
0      40    1                2  ...                0      0.0         1
1      49    0                3  ...                0      1.0         2
2      37    1                2  ...                0      0.0         1
3      48    0                4  ...                1      1.5         2
4      54    1                3  ...                0      0.0         1
...   ...  ...              ...  ...              ...      ...       ...
1185   45    1                1  ...                0      1.2         2
1186   68    1                4  ...                0      3.4         2
1187   57    1                4  ...                1      1.2         2
1188   57    0                2  ...                0      0.0         2
1189   38    1                3  ...                0      0.0         1

[1190 rows x 11 columns]
0       0
1       1
2       0
3       1
4       0
       ..
1185    1
1186    1
1187    1
1188    

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
print(X_train.shape, X_test.shape)

(952, 11) (238, 11)


In [ ]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression(solver='lbfgs', max_iter=1000)
logReg.fit(X_train, Y_train)

Y_pred = logReg.predict(X_test)
print(Y_test, Y_pred)

1149    0
734     1
1117    0
585     1
750     1
       ..
542     1
153     0
5       0
1       1
509     1
Name: target, Length: 238, dtype: int64 [0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 0 1 1 1 0 0 1 0 1 1 0 0 0 1 1 0 1 0 0
 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0
 0 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1
 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 1 1
 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 1
 1 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0
 1 0 0 1 0 0 0 1 1 0 1 1 0 0 0 1]


In [ ]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred)) 
print("Precision:\n", precision_score(Y_test, Y_pred, average=None))
print("Recall:\n", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[ 93  12]
 [ 24 109]]
Accuracy:
 0.8487394957983193
Precision:
 [0.79487179 0.90082645]
Recall:
 [0.88571429 0.81954887]


In [ ]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[71 34]
 [45 88]]
Accuracy:
 0.6680672268907563


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_dtc)) 

Confusion Matrix:
 [[ 97   8]
 [ 14 119]]
Accuracy:
 0.907563025210084


In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))


Confusion Matrix:
 [[ 99   6]
 [  7 126]]
Accuracy:
 0.9453781512605042
